export const ActionTypes = {
  FETCH_PREFS: "PREFS_ACTIONS/FETCH_PREFS",
  FETCH_POPULATION: "POPLATION_ACTIONS/FETCH_POPULATION",
  DELETE_POPULATION: "POPLATION_ACTIONS/DELETE_POPULATION",
} as const;
